services:
  backend:
    container_name: sync-track-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  redis:
    container_name: sync-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
